import Head from "next/head";
import SideMenu from "./SideMenu/SideMenu";
// @ts-ignore
import Landing from "./landing/landing";
import DappBar from "./Navbar/DappBar";

import ApproveModal from "./Stuff/ApproveModal";
import Layout from "@/components/Layout";

export default function Home() {
  return (
    <div className={"dappMainDiv"}>
      <Head>
        <title>Kindred Dapp</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter&family=Montserrat:ital,wght@0,300;0,500,700;0,900;1,400&family=Roboto:wght@700&family=Ubuntu:wght@300;400&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Layout>
        <ApproveModal />
      </Layout>
    </div>
  );
}
