import Head from 'next/head';
// @ts-ignore
import Landing from './landing/landing';
import DappBar from './Navbar/DappBar';

import ApproveModal from './Stuff/ApproveModal';


export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>Kindred Dapp</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header style={{ padding: '1rem' }}>
        <DappBar />
      </header>

      <main
        style={{
          minHeight: '60vh',
          flex: '1',
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center',
          backgroundColor: '#ECEEFF'
        }}
      >
        <ApproveModal />

        <footer />
      </main>
    </div>
  );
}
